### ISSUE TITLE
VibeCheck

### ISSUE THREAD

**Issue by aklidata** [PullDating/Org#73]
### Discussed in https://github.com/PullDating/Org/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **WilliamDormer** May 17, 2022</sup>
[Zack/boobpocket edit]
###Vibe Check - A new matching mechanism: 
-----------------------------------------------

The idea behind Vibe Check is is to make matching more engaging and upgrade the quality of matches. 

It started off after I used several dating services and suffering from dating fatigue due to having to sort through several low quality matches. The biggest offenders are Tinder, Bumble and other Purely superficial dating apps where you swipe mainly based on appearance and figure out the rest afterwards. 

The second goal for Vibe Check is to temper primal instincts and to slow down the matching process, serving two purposes: 

1. The available dating pool does not get depleted so fast due to user excessive swiping. 
2. People in a mood for something more nefarious will have to put in more effort which might function as a deterrent. 

This feature/mechanism will be a net positive for the romance/dating part of the project. Serving to truly separate the hookup portion from the serious daters. 

=====================================================
To make matching less superficial, add the option for people to put a questionnaire on their profile that is shown to potential matches before they actually see their photos. This way, they can verify that they'll vibe with the people they are matching with to reduce the number of low-quality matches.</div>

**Comment by WilliamDormer** [comment]
closing because it's not really a "todo" issue. Maybe make an entry in fibery with the same information zack.
